### ISSUE TITLE
Is paper in sweave or knitr format?

### ISSUE THREAD

**Issue by hadley** [COSTDataExpo2013/AmeliaMN#1]
It doesn't work with sweave, and with knitr, it gives a message asking you to run `Sweave2knitr`

**Comment by hadley** [comment]
Maybe all you need to do is remove `\SweaveOpts{concordance=TRUE}` ?

**Comment by hadley** [comment]
Also it might be worthwhile checking in an RStudio project file?

**Comment by AmeliaMN** [comment]
It should be in knitr format, and I don't see `\SweaveOpts{concordance=TRUE}` either in my local version or on github. 

re: .Rproj file, I was not sure how much embarrassing code history was going to come along with that. What's the benefit in this instance?

**Comment by hadley** [comment]
Oh hmmm, maybe RStudio added it when I tried to knit it?

There's nothing in the .Rproj apart from project settings, so it's generally a good idea to include. In this instance you could make sure the project settings defaulted to using knitr, not sweave.
