### ISSUE TITLE
dplyr would be better here...

### ISSUE THREAD

**Issue by hadley** [COSTDataExpo2013/AmeliaMN#8]
Here's one way to formulate it:

``` R
sotc10 %>%
  select(one_of(twolevel)) %>%
  mutate(id = 1:n()) %>%
  tidyr::gather("Question", "Response", -id) %>%
  group_by(Question, Response) %>%
  summarise(n = n())
```

**Comment by hadley** [comment]
I think you can to apply the same idea to `citystateResp`.

**Comment by AmeliaMN** [comment]
Ha, looking back at my code I can see my comment, 
`#dplyr would be much better here, but can't quite figure out how to formulate it.` 
Thanks for the suggestion, will try.
